apiVersion: v1
kind: Service
metadata:
  name: {{ include "ash.fullname" . }}-headless
  labels:
    {{- include "ash.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.ash.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ash.selectorLabels" . | nindent 4 }}
